Training:
  Num_epochs: 5 
  per_device_train_batch_size: 4
  per_device_eval_batch_size: 4
  weight_decay: 0.01 
  evaluation_strategy: epoch
  metric_for_best_model: eval_loss
  gradient_accumulation_steps: 2 